# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '183fb60b-4768-4afd-9b1c-8babb162488b'
  imageRepository: 'shoppingapi'
  containerRegistry: 'dimshoppingacr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'dimshoppingacr175737ec-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo ">>> Installing QEMU for cross-platform builds"
        docker run --privileged --rm tonistiigi/binfmt --install all

        echo ">>> Creating and bootstrapping buildx builder"
        docker buildx create --use --driver docker-container --name mybuilder
        docker buildx inspect mybuilder --bootstrap

        echo ">>> Building and pushing ARM64 image"
        docker buildx build --platform linux/arm64 \
          -t $(containerRegistry)/$(imageRepository):$(tag) \
          -f Shopping.API/Dockerfile \
          --push Shopping.API
      displayName: Build and push ARM64 image

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'dsliesarenkoShopping.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/shoppingapi.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

